apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: smoketest-{{ include "custom-app.fullname" . }}-
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: smoke-test
  templates:
  - name: smoke-test
    steps: 
      - - name: smoke-test
          templateRef: 
            name: smoke-test
            template: smoke-test 
          arguments:
            parameters:
              - name: servicename
                value: {{ include "custom-app.fullname" . }}
              - name: namespace
                value: argo-samples
              - name: port
                value: {{ .Values.service.port }}
