apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: smoketest-{{ include "custom-app.fullname" . }}-
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: smoke-test
  templates:
  - name: smoke-test
    steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
      - - name: smoke-test
          templateRef:                  # You can reference a "template" from another "WorkflowTemplate" using this field
            name: smoke-test  # This is the name of the "WorkflowTemplate" CRD that contains the "template" you want
            template: smoke-test # This is the name of the "template" you want to reference
          arguments:                    # You can pass in arguments as normal
            parameters:
              - name: servicename
                value: {{ include "custom-app.fullname" . }}
              - name: namespace
                value: alpha-platform
              - name: port
                value: {{ .Values.service.port }}
