apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  project: default
  source:
    path: third-party/vault-set/chart
    repoURL: git@github.com:jrhoward/argo-sample-app.git
    targetRevision: HEAD
    helm:
      releaseName: 'dev-vault'
      version: v3
      valueFiles:
      -  values/dev/values.yaml
      parameters:
      - name: namespacePass
        value: dev-vault
  destination:
    server: https://kubernetes.default.svc
    namespace: 'dev-vault'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas