apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: third-party/vault-base/
    repoURL: git@github.com:jrhoward/argo-sample-app.git
    targetRevision: HEAD
    helm:
      releaseName: vault-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
