apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-app-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: custom-apps/custom-app-set/chart
    repoURL: https://github.com/jrhoward/argo-sample-app.git
    targetRevision: HEAD
    helm:
      releaseName: 'custom-app-3'
      version: v3
      valueFiles:
      -  values/dev/custom-app-3.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 'argo-samples'
  syncPolicy:
    # automated:
    #   prune: true
    #   #allowEmpty: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas